"""empty message

Revision ID: 109febeb42ef
Revises: 1f3af0835b0c
Create Date: 2023-08-31 07:07:26.759879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109febeb42ef'
down_revision = '1f3af0835b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
