"""empty message

Revision ID: 14e3a4f67734
Revises: baec676aab09
Create Date: 2023-08-26 09:06:49.845547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e3a4f67734'
down_revision = 'baec676aab09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_name', sa.String(), nullable=False),
    sa.Column('prix_total', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usersdata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payement')
    # ### end Alembic commands ###
