"""empty message

Revision ID: 1c2a70d8c7db
Revises: 00bd718f1eb2
Create Date: 2023-09-10 21:30:51.754822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2a70d8c7db'
down_revision = '00bd718f1eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promotion_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('articles_promotion_article_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'promotions', ['promotion_id'], ['id'])
        batch_op.drop_column('promotion_article_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promotion_article_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('articles_promotion_article_id_fkey', 'promotions', ['promotion_article_id'], ['id'])
        batch_op.drop_column('promotion_id')

    # ### end Alembic commands ###
