"""empty message

Revision ID: 2128e2e1b300
Revises: ad0737840bae
Create Date: 2023-08-19 12:16:34.530136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2128e2e1b300'
down_revision = 'ad0737840bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('nbr_de_likes')
        batch_op.drop_column('nbr_de_vues')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nbr_de_vues', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nbr_de_likes', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
