"""empty message

Revision ID: 22c5a455cd84
Revises: 130e16ec3760
Create Date: 2023-09-04 21:31:33.096399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c5a455cd84'
down_revision = '130e16ec3760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Commentaires',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_of_commentateur', sa.String(length=20), nullable=False),
    sa.Column('name_of_commentateur', sa.String(length=20), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Commentaires')
    # ### end Alembic commands ###
