"""empty message

Revision ID: 2bd5f07136ab
Revises: 877902f552ee
Create Date: 2023-09-04 19:58:09.104011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd5f07136ab'
down_revision = '877902f552ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_de_vues', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('nombre_de_vues')

    # ### end Alembic commands ###
