"""empty message

Revision ID: 2ed54cb86e12
Revises: 243aea6078ea
Create Date: 2023-08-15 13:07:34.073610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed54cb86e12'
down_revision = '243aea6078ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('Username', sa.String(), nullable=False),
    sa.Column('Password', sa.String(), nullable=False),
    sa.Column('inscription_time', sa.DateTime(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Password'),
    sa.UniqueConstraint('Username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersdata')
    # ### end Alembic commands ###
