"""empty message

Revision ID: 3f3b2881d752
Revises: 06de392f513a
Create Date: 2023-09-03 09:20:24.080550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3b2881d752'
down_revision = '06de392f513a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('articleId', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('duree_de_la_promo', sa.String(), nullable=False))
        batch_op.drop_column('details')
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('duree_de_la_promo')
        batch_op.drop_column('articleId')

    # ### end Alembic commands ###
