"""empty message

Revision ID: 55e21eb6ee7f
Revises: 3511b40ef300
Create Date: 2023-09-05 10:39:05.505266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e21eb6ee7f'
down_revision = '3511b40ef300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articlesfavoris', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_of_user', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_of_article', sa.Integer(), nullable=True))
        batch_op.drop_constraint('articlesfavoris_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('articlesfavoris_article_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usersdata', ['id_of_user'], ['id'])
        batch_op.create_foreign_key(None, 'articles', ['id_of_article'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('article_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articlesfavoris', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('articlesfavoris_article_id_fkey', 'articles', ['article_id'], ['id'])
        batch_op.create_foreign_key('articlesfavoris_user_id_fkey', 'usersdata', ['user_id'], ['id'])
        batch_op.drop_column('id_of_article')
        batch_op.drop_column('id_of_user')

    # ### end Alembic commands ###
