"""empty message

Revision ID: 5be93de65414
Revises: 1b63b14562ea
Create Date: 2023-08-30 09:30:28.431233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be93de65414'
down_revision = '1b63b14562ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usersdata', ['user_id'], ['id'])

    with op.batch_alter_table('usersdata', schema=None) as batch_op:
        batch_op.drop_constraint('usersdata_user_panier_fkey', type_='foreignkey')
        batch_op.drop_column('user_panier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_panier', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('usersdata_user_panier_fkey', 'panier', ['user_panier'], ['id'])

    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
