"""empty message

Revision ID: 5cccafe465eb
Revises: 8ea7db90f60f
Create Date: 2023-08-21 22:45:39.799532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cccafe465eb'
down_revision = '8ea7db90f60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.drop_constraint('panier_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.create_unique_constraint('panier_user_id_key', ['user_id'])

    # ### end Alembic commands ###
