"""empty message

Revision ID: 5e8641fb8dee
Revises: dffd55ee5cbb
Create Date: 2023-09-28 09:48:45.899734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8641fb8dee'
down_revision = 'dffd55ee5cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentaires', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
