"""empty message

Revision ID: 5fdb42a7ea56
Revises: a44c4977fe97
Create Date: 2023-09-22 21:22:50.632608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fdb42a7ea56'
down_revision = 'a44c4977fe97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commentaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('Commentaires_id_of_commentateur_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usersdata', ['user_id'], ['id'])
        batch_op.drop_column('id_of_commentateur')
        batch_op.drop_column('name_of_commentateur')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commentaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_of_commentateur', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_of_commentateur', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Commentaires_id_of_commentateur_fkey', 'usersdata', ['id_of_commentateur'], ['id'])
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
