"""empty message

Revision ID: 6649f23dc1b4
Revises: bfe24b4cc58a
Create Date: 2023-12-27 16:58:17.489494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6649f23dc1b4'
down_revision = 'bfe24b4cc58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=22),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('Description',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('Description',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=22),
               existing_nullable=False)

    # ### end Alembic commands ###
