"""empty message

Revision ID: 71945a4b72a7
Revises: 5fdb42a7ea56
Create Date: 2023-09-22 21:56:08.015332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71945a4b72a7'
down_revision = '5fdb42a7ea56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentaires',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commentaires', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usersdata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Commentaires')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Commentaires',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Commentaires_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('commentaires', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='Commentaires_article_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['usersdata.id'], name='Commentaires_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Commentaires_pkey')
    )
    op.drop_table('commentaires')
    # ### end Alembic commands ###
