"""empty message

Revision ID: 7a888f6965c8
Revises: a58721392f96
Create Date: 2023-08-13 22:21:56.506528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a888f6965c8'
down_revision = 'a58721392f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.Column('Statut', sa.Boolean(), nullable=False),
    sa.Column('date_arrive', sa.Date(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(), nullable=False),
    sa.Column('Password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Password'),
    sa.UniqueConstraint('Username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_data')
    op.drop_table('Articles')
    # ### end Alembic commands ###
