"""empty message

Revision ID: 877902f552ee
Revises: 20ee86dc855b
Create Date: 2023-09-03 17:28:35.718838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877902f552ee'
down_revision = '20ee86dc855b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articleId', sa.Integer(), nullable=False),
    sa.Column('duree_de_la_promo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'promotions', ['promotion_article_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('promotions')
    # ### end Alembic commands ###
