"""empty message

Revision ID: 8cba56f97277
Revises: a6c6a9fd807c
Create Date: 2023-08-29 23:22:06.612296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cba56f97277'
down_revision = 'a6c6a9fd807c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('imagedefilante')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promotion_article_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'promotions', ['promotion_article_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('promotion_article_id')

    op.create_table('imagedefilante',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='imagedefilante_pkey')
    )
    op.drop_table('promotions')
    op.drop_table('promotion')
    # ### end Alembic commands ###
