"""empty message

Revision ID: a44c4977fe97
Revises: 3e84b86262d5
Create Date: 2023-09-22 19:03:53.677508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44c4977fe97'
down_revision = '3e84b86262d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commentaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaires', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commentaires', schema=None) as batch_op:
        batch_op.drop_column('commentaires')

    # ### end Alembic commands ###
