"""empty message

Revision ID: a7667dc9c6ea
Revises: 92743acabf2a
Create Date: 2023-09-04 22:09:49.208956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7667dc9c6ea'
down_revision = '92743acabf2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Commentaires',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_of_commentateur', sa.Integer(), nullable=False),
    sa.Column('name_of_commentateur', sa.String(length=20), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['id_of_commentateur'], ['usersdata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Commentaires')
    # ### end Alembic commands ###
