"""empty message

Revision ID: ad0737840bae
Revises: ba838667ea39
Create Date: 2023-08-18 22:54:59.550868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0737840bae'
down_revision = 'ba838667ea39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nbr_de_likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nbr_de_vues', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('nbr_de_vues')
        batch_op.drop_column('nbr_de_likes')

    # ### end Alembic commands ###
