"""empty message

Revision ID: b82ee02820b3
Revises: 2ed54cb86e12
Create Date: 2023-08-16 08:43:35.309504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82ee02820b3'
down_revision = '2ed54cb86e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Biographie', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersdata', schema=None) as batch_op:
        batch_op.drop_column('Biographie')

    # ### end Alembic commands ###
