"""empty message

Revision ID: ba838667ea39
Revises: bbf54c6a44f6
Create Date: 2023-08-18 22:53:47.691783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba838667ea39'
down_revision = 'bbf54c6a44f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nbr_de_likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nbr_de_vues', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('nbr_de_vues')
        batch_op.drop_column('nbr_de_likes')

    # ### end Alembic commands ###
