"""empty message

Revision ID: baec676aab09
Revises: 86c8b8cb37cc
Create Date: 2023-08-25 19:02:13.257269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baec676aab09'
down_revision = '86c8b8cb37cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint('articles_user_name_fkey', type_='foreignkey')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('articles_user_name_fkey', 'usersdata', ['user_name'], ['Username'])

    # ### end Alembic commands ###
