"""empty message

Revision ID: c5f1524cbfa0
Revises: 2128e2e1b300
Create Date: 2023-08-20 20:39:43.140474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f1524cbfa0'
down_revision = '2128e2e1b300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usersdata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_paniers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('panier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['panier_id'], ['panier.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usersdata.id'], )
    )
    with op.batch_alter_table('usersdata', schema=None) as batch_op:
        batch_op.drop_constraint('usersdata_Password_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersdata', schema=None) as batch_op:
        batch_op.create_unique_constraint('usersdata_Password_key', ['Password'])

    op.drop_table('users_paniers')
    op.drop_table('panier')
    # ### end Alembic commands ###
