"""empty message

Revision ID: ca53a28ab038
Revises: e7fb2e1fe759
Create Date: 2023-09-04 22:06:21.237311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca53a28ab038'
down_revision = 'e7fb2e1fe759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Commentaires')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Commentaires',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Commentaires_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_of_commentateur', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name_of_commentateur', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Commentaires_pkey')
    )
    # ### end Alembic commands ###
