"""empty message

Revision ID: cbc82597d8ca
Revises: 22c5a455cd84
Create Date: 2023-09-04 21:49:41.616721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc82597d8ca'
down_revision = '22c5a455cd84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commentaires', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usersdata', ['id_of_commentateur'], ['id'])
        batch_op.create_foreign_key(None, 'articles', ['article_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commentaires', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
