"""empty message

Revision ID: d64a41fa3904
Revises: e2a9bfb0d531
Create Date: 2023-09-01 14:39:04.467254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64a41fa3904'
down_revision = 'e2a9bfb0d531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_column('article_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
