"""empty message

Revision ID: dffd55ee5cbb
Revises: 71945a4b72a7
Create Date: 2023-09-28 08:58:24.276456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffd55ee5cbb'
down_revision = '71945a4b72a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentaires', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
