"""empty message

Revision ID: e2a9bfb0d531
Revises: 109febeb42ef
Create Date: 2023-09-01 14:21:37.009831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a9bfb0d531'
down_revision = '109febeb42ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_column('article_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
