"""empty message

Revision ID: e6a2a92ff2b1
Revises: 9b45effd38c0
Create Date: 2023-08-21 19:50:21.930728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a2a92ff2b1'
down_revision = '9b45effd38c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.drop_constraint('panier_article_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'articles', ['article_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('panier_article_id_fkey', 'articles', ['article_id'], ['id'])

    # ### end Alembic commands ###
