"""empty message

Revision ID: e7fb2e1fe759
Revises: cbc82597d8ca
Create Date: 2023-09-04 21:51:38.600923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fb2e1fe759'
down_revision = 'cbc82597d8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commentaires', schema=None) as batch_op:
        batch_op.alter_column('id_of_commentateur',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'articles', ['article_id'], ['id'])
        batch_op.create_foreign_key(None, 'usersdata', ['id_of_commentateur'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commentaires', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_of_commentateur',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
