"""empty message

Revision ID: edfb5fc781e0
Revises: 5cccafe465eb
Create Date: 2023-08-22 17:33:03.720564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfb5fc781e0'
down_revision = '5cccafe465eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('Statut')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Statut', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
