"""empty message

Revision ID: f095548558c2
Revises: da00ca90ba88
Create Date: 2023-12-27 15:51:34.369343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f095548558c2'
down_revision = 'da00ca90ba88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=False)

    with op.batch_alter_table('usersdata', schema=None) as batch_op:
        batch_op.alter_column('Biographie',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersdata', schema=None) as batch_op:
        batch_op.alter_column('Biographie',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
