"""empty message

Revision ID: f51f988e8959
Revises: a0f0ee2e8805
Create Date: 2023-08-21 21:27:36.210781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51f988e8959'
down_revision = 'a0f0ee2e8805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'usersdata', ['user_id'], ['id'])

    with op.batch_alter_table('usersdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panier_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['panier_id'])
        batch_op.create_foreign_key(None, 'panier', ['panier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersdata', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('panier_id')

    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
